### ISSUE TITLE
Issue with subscriber marker

### ISSUE THREAD

**Issue by victorguilhermeo** [darsain/twitch-giveaways#31] opened 2016-06-19 05:07 UTC
Hi, recently some streamers are encountering problems with the extension. Somehow sometimes, even if the twitch user is a subscriber it doesnt show the green checkmark for them, instead it shows the grey X mark.
I already noticed this issue on 3 streamers, JoshOG, Phantoml0rd and Dinglederper.

Just trying to help out and feedback this issue. Thank you for the attention.

**Comment by darsain** [comment] 2016-06-19 09:50
Closing as duplicate of #29 and #30.

tl;dr: BTTV breaks TGA. You have to pick one, or run TGA in an incognito mode.

**Closed by darsain** 2016-06-19 09:50 UTC

**Comment by victorguilhermeo** [comment] 2016-06-19 22:28
That has never been an Issue before, but why is it happening now?
Is there any way to fix? Or it was something new that BTTV changed that
breaks the TGA?

2016-06-19 6:50 GMT-03:00 darsain <notifications@github.com>:

**Comment by darsain** [comment] 2016-06-19 22:43
There was a Twitch chat DOM structure change, and TGA had to adapt a few days ago. Since than TGA doesn't 100% work when BTTV is installed. I assume BTTV is replacing chat DOM with its own structure (specifically the badge icons) which is different than what TGA is trying to parse.

**Comment by victorguilhermeo** [comment] 2016-06-19 23:45
Can't you implement a way to check if the user is using BTTV or not (or
maybe checking if the structure is changed)? If changed, do the procedures
to correctly parse the sub icon, if

2016-06-19 19:43 GMT-03:00 darsain <notifications@github.com>:

**Comment by darsain** [comment] 2016-06-20 09:54
Yes, that is certainly doable. Reason why it's not happening is stated in #29.
