### ISSUE TITLE
Giveaways is not detecting my subscribers

### ISSUE THREAD

**Issue by basarcos** [darsain/twitch-giveaways#32] opened 2016-06-19 23:13 UTC
Hello,
This is quite recent. A few days ago I distributed some HS booster packs with the extension and it seemed to be working fine. Today it just didn't detect my subscribers and therefore I couldn't use subscriber luck. I disabled and enabled it, I also tried removing and reinstalling. No luck.
Any help would be appreciated, regards,
Basar.

**Comment by darsain** [comment] 2016-06-20 09:51
Closing as duplicate of #29, #30, #31.

tl:dr: BTTV breaks TGA. Either disable BTTV, or enable TGA to run in incognito mode, and run giveaways there.

**Closed by darsain** 2016-06-20 09:51 UTC
