### ISSUE TITLE
Subscribers do not show up as subscribers in raffle anymore.

### ISSUE THREAD

**Issue by ProtostarMusic** [darsain/twitch-giveaways#29] opened 2016-06-15 21:03 UTC
Any subscriber that is raffled does not show that they are subbed, am unsure if sub luck is also not applied to them.

**Comment by darsain** [comment] 2016-06-15 21:15
Just tested, and everything works for me:

![test](https://i.imgur.com/Oy4Zwzz.png)

So unless you properly describe the issue with steps how to reproduce, I'm gonna close this.

**Comment by ProtostarMusic** [comment] 2016-06-15 21:24
As you can see samj is a sub in the chat but does not appear.
no subs come up as subs in teh window. have removed plugin and reinstalled too.
http://i.imgur.com/1e8w3Wn.png

**Comment by ProtostarMusic** [comment] 2016-06-15 21:25
There are no steps to reproduce unfortunately, both me and @xilent are having this issue in both our streams.

**Comment by ProtostarMusic** [comment] 2016-06-15 21:25
https://www.twitch.tv/xilent

**Comment by ProtostarMusic** [comment] 2016-06-15 21:26
i get the same error on my stream as you can see here:
http://i.imgur.com/eXdwL8R.png

**Comment by darsain** [comment] 2016-06-15 21:31
It looks like you are running an old version with issue #27 where people badges and groups are not recognized. It got fixed yesterday. Weird that it didn't update for you yet.

You can always update manually tho. Go to More tools -> Extensions, check Developer mode, and click on update extensions.

The current TGA version is 2.6.0

**Comment by ProtostarMusic** [comment] 2016-06-15 21:34
strange, cant update, even restarted chrome via task manager too:
https://gfycat.com/SpiffyGreenCuttlefish

**Comment by darsain** [comment] 2016-06-15 21:42
Oh, sorry, the latest is 2.5.0, so you are already on it. And still having those issues?

**Comment by ProtostarMusic** [comment] 2016-06-15 21:44
yup :/
http://i.imgur.com/YtX9hyP.png

**Comment by darsain** [comment] 2016-06-15 22:01
Are you running some other twitch extensions? If so, could you try disabling them and try again?

Btw, did you reload the whole chat and reopened the giveaways after update?

**Comment by ProtostarMusic** [comment] 2016-06-15 22:06
diabling twitch plugins worked. 
Plugins i disabled are
https://chrome.google.com/webstore/detail/betterttv/ajopnjidmegmdimjlfnijceegpefgped?utm_source=chrome-app-launcher-info-dialog

https://chrome.google.com/webstore/detail/frankerfacez/fadndhdgpmmaapbmfcknlfgcflmmmieb?utm_source=chrome-app-launcher-info-dialog

https://chrome.google.com/webstore/detail/twitchalerts-stream-label/kgmggmdngboajiakmbpdknfpdelbjbcg?utm_source=chrome-app-launcher-info-dialog

Ill try pinpoint which plugin is causing the clash

**Comment by ProtostarMusic** [comment] 2016-06-15 22:08
seems like its better twitch tv causing the issue.

**Comment by darsain** [comment] 2016-06-15 22:11
Oh well, doesn't really matter which one it is. I don't really have time to make this extension compatible with all current and future extensions that touch twitch chat DOM. I advise not using that particular extension if at all possible.

Alternative solution could be enabling twitch giveaways in incognito mode (no extension run there by default), and whenever you wanna run a giveaway you open chat in incognito. This way you have a clean browser environment where only twitch giveaway is running.

Gonna close this as this issue is not related to TGA. Feel free to report which extension caused the problem for anyone looking thought this in future.

**Closed by darsain** 2016-06-15 22:11 UTC

**Comment by ProtostarMusic** [comment] 2016-06-15 22:16
I told you that its Better twitch tv. And as it was your plugin that was broken from an update it isnt their fault.
BTTV is THE biggest twitch plugin and to not make it compatible is a bit silly in my opinion.
A lot of people including me use 2FA on our twitch accounts and dont have the time to log in to our accounts in incognito every time.

I plead you to try fix this issue or a lot of us twitch partners may sadly have to go use other solutions :/ Which is a shame because i really liked this plugin.

**Comment by darsain** [comment] 2016-06-15 22:31
You don't need to log into the chat to run giveaway in it. All you need is to open it.

And again, I struggle to find time to even fix bugs here. Can't justify supporting compatibility with other extensions. I'm already irritated when twitch makes changes which break TGA. Supporting other extensions would multiply this workload. So, unless you are willing to fund the development time this would require, I'm afraid this is not gonna happen.

I wish working on stuff like this would pay the bills, but despite this extension being used by 100k people, only around 10 of them decided to support its development. Didn't even cover 1% of the development that went into it.

**Comment by ProtostarMusic** [comment] 2016-06-15 22:37
Fair enough i get that.

I was thinking that because you knew what the issue was before that it would be a similar fix to have worked with the BTTV plugin. (and as it was working fine before with bttv too)

Sorry about the plugin coding not paying the bills, i feel you on that, independent artist that barely gets by. Sorry for the any bad comments on my part.

Kind Regards

**Comment by bradgrafelman** [comment] 2016-06-17 19:10
Just in case someone else wants to try to help debug this one... I've gotten as far as the MutationObserver in src/js/lib/chat.js. Without BTTV, a chat line results in 7 MutationRecord objects; with BTTV enabled, it only results in 1.

The one that gets all the way to the filter() that sets the badges property looks radically different. Here's the innerHTML with BTTV disabled:
`"<div class="indicator"></div>↵<!---->  <span class="timestamp float-left">1:57</span>↵<!---->↵  <span class="badges float-left">↵      <a rel="noopener" target="_blank">↵        <span id="ember886" class="ember-view"><img class="badge-img tooltip" src="https://static-cdn.jtvnw.net/badges/v1/3267646d-33f0-4b17-b3df-f923a41db1d0/1" original-title="Moderator">↵</span>↵      </a>↵  </span>↵  <span class="from" style="color:#DAA520" data-ember-action="887">BradGbot</span>↵  <span class="colon">:</span>↵<span class="message" style="">↵          test↵            </span>"`

but here it is with BTTV enabled:

`"<span class="timestamp"><small>1:52</small></span> <span class="mod-icons"><a class="mod-icon ban" title="Ban">Ban</a><a class="mod-icon unban" title="Unban" style="display: none;">Unban</a><a class="mod-icon timeout" title="Timeout">Timeout</a></span> <span class="badges"><div class="moderator badge" title="Channel Moderator"></div> </span><span style="color: #1E90FF;" class="from">BradGbot</span><span class="colon">:</span>&nbsp;<wbr><span class="message " data-raw="test5" data-emotes="%7B%7D">test5</span>"`

So... looks like BTTV is radically changing the DOM; most notably, it's removing the <img>'s with "badge-img" class and instead replacing them with <div>'s that it presumably later styles with the appropriate image (using a background image + color rather than an <img> element).

**Comment by darsain** [comment] 2016-06-17 22:14
@bradgrafelman oh man TGA code is a mess, so sorry you had to go through it :) I'm very embarrassed.
